version: "3.9"
services:
  authdb:
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "authdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd4auth"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: authdb
    volumes:
      - authdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - authdb
    volumes:
      - ./src:/app/src

volumes:
  authdb-data:
